function(check_ansi_c var)
	message(STATUS "Checking whether system has ANSI C header files")
	include(CheckFunctionExists)
	include(CheckIncludeFiles)

	check_include_files("stdlib.h;stdarg.h;string.h;float.h" StandardHeadersExist)
	if(StandardHeadersExist)
		check_function_exists(memchr memchrExists)
		if(memchrExists)
			check_function_exists(free freeExists)
			if(freeExists)
				message(STATUS "ANSI C header files - found")
				set(var 1 CACHE INTERNAL "System has ANSI C header files")
			endif(freeExists)
		endif(memchrExists)
	endif(StandardHeadersExist)

	if(NOT var)
		message(STATUS "ANSI C header files - not found")
		set(var "" CACHE INTERNAL "System has ANSI C header files")
	endif(NOT var)
endfunction()